name: Export Source Translations

on:
  push:
    branches:
      - master

jobs:
  export-source-translations:
    name: Update translations branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run export script
        run: |
          sh devtools/export-source-translation.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Translations 🤖
          branch: translations
          create_branch: true
          push_options: '--force'
        if: env.GIT_DIFF
